### PR TITLE
 Add groupName to AccountPoolMapper class (SOFTWARE-2047)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by edquist** [comment]
@bbockelm, I'm doing a separate PR here without the extra retrieveMapping stuff from #21

**Comment by bbockelm** [comment]
Implementation looks good now.  What testing did you perform?

(PS - for future reference, if you do a forced update, github will update an existing PR appropriately.  We can keep with this one for now though)

**Comment by edquist** [comment]
I haven't done any functional tests of the new feature -- can you suggest a basic testing recipe?  (Mapping with a groupName configured should just return the group name now, right?)

**Comment by bbockelm** [comment]
Yeah, try this:
1.  Take the latest template and load it into GUMS.  Update all the VO groups.
2.  Add a simple host-to-group mapping for foo.example.com and include at least one pool mapper.
3.  Add a group name to the pool mapper.
4.  Do a mapping through the webpage.  Look at the logs and make sure a group name is returned.
5.  Remove the group name from the pool mapper.
6.  Make sure no group name is returned.

Repeat (5) and (6), making sure the group name is not in the XML file.

**Comment by edquist** [comment]
For 2: "include at least one pool mapper" -- I can add a list of "Group To Account Mapping(s)" on the Host To Group edit page, but it doesn't seem to allow adding poll mappers.

Am I missing something simple?

**Comment by edquist** [comment]
Here's what I did step-by-step.  (Let me know if I'm missing something..!)

1. [Account Mappers], [add]
 - Name: TEST_POOL_ACCT_MAPPER
 - Type: pool
 - Group: 123456
 - [save]

2. [Group To Account Mappings], [add]
 - Name: TEST_GRP_TO_ACCT_MAPPING
 - User Group(s): admins   (includes my DN)
 - Account Mapper(s): TEST_POOL_ACCT_MAPPER
 - [save]

3. [Host To Group Mappings], [add]
 - Hosts: foo.example.com     cn (x) dn ( )
 - Group To Account Mapping(s): TEST_GRP_TO_ACCT_MAPPING
 - [save]

4. [Map Grid Identity to Account]
 - DN (Distinguished Name) for service: /DC=com/DC=example/OU=Services/CN=foo.example.com
 - DN (Distinguished Name) for user: /DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013
 - [map user]

Result:

On '/DC=com/DC=example/OU=Services/CN=foo.example.com', '/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013' is mapped to:
null

**Comment by edquist** [comment]
@bbockelm, I misunderstood earlier thinking that the groupName would be returned on the webpage also when doing the mapping, so I was worried it was not working when all I saw was **null** returned.

But the mapping with the groupName does appear in gums-service-admin.log, and removing the group name from the pool mapper does stop a groupName from being returned, and the groupName attribute gets removed from the accountPoolMapper in the XML.

So it seems to pass the test.

Two oddities though:

1. the first time the user gets mapped to the pool account (with the groupName), no group shows up in the log, but it does in all subsequent attempts for the given user:

        30 Sep 2015 01:21:08,171 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 77777' / 'null' to 'Account[user=myAccount001]'
        30 Sep 2015 01:21:39,179 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 77777' / 'null' to 'Account[user=myAccount001, group=9999]'
        
        30 Sep 2015 01:22:37,582 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345' / 'null' to 'Account[user=myAccount002]'
        30 Sep 2015 01:23:01,526 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345' / 'null' to 'Account[user=myAccount002, group=9999]'
        30 Sep 2015 01:23:16,688 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345' / 'null' to 'Account[user=myAccount002, group=9999]'
        30 Sep 2015 01:25:33,238 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345' / 'null' to 'Account[user=myAccount002, group=9999]'

2. after removing the group name from the pool mapper, the log shows "group=" instead of just not showing the group field at all:

        30 Sep 2015 01:28:49,868 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345' / 'null' to 'Account[user=myAccount002, group=]'
        30 Sep 2015 01:29:49,815 [INFO ]: GridID[/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013] - Mapped on host '/DC=com/DC=example/OU=Services/CN=foo.example.com' the user '/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345' / 'null' to 'Account[user=myAccount002, group=]'

Are either of these problems?

**Comment by edquist** [comment]
Think I found the answer to my two questions  :)

**Comment by edquist** [comment]
Yeah, I made a new build with these changes and everything's working as expected now.

**Pull request merged**
